#+title: Liblouis release helpers

A script to generate some of the artifacts needed for a liblouis
release. In particular it creates

- An up-to-date ANNOUNCE file containing the news from NEWS
- a news post that can be inserted in the Jekyll based web site
- an up-to-date download index
- an up-to-date online documentation

* Usage

First build liblouis

#+BEGIN_SRC shell
cd ~/src/liblouis
make dist
#+END_SRC

Then run the release-helper script. Specify where the source to
liblouis and the liblouis website is located

#+BEGIN_SRC shell
clj -m release-helper ~/src/liblouis ~/src/liblouis.github.io
#+END_SRC

* Prerequisites

- You need the Clojure cli tools. Install them tools as described in
  the [[https://clojure.org/guides/getting_started][Getting Started Guide]].
- You need [[https://pandoc.org/][pandoc]].
- I recommend you use [[https://hub.github.com/][hub]] to create github releases from the command
  line

* Contributing
If you have any improvements or comments please feel free to file a
pull request or an issue.

* License

Copyright (C) 2019 Swiss Library for the Blind, Visually Impaired and Print Disabled

This library is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or (at
your option) any later version.

This library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this library; see the file COPYING. If not, write to the Free
Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
02110-1301 USA

